# Generated by Django 3.1.2 on 2020-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Product_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=40)),
                ('MRP', models.FloatField()),
                ('Price', models.FloatField()),
                ('Stock_Balance', models.IntegerField()),
                ('Discount', models.FloatField()),
            ],
        ),
    ]
