# Generated by Django 3.1.2 on 2020-10-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_No', models.IntegerField()),
                ('Timestamp', models.CharField(max_length=10)),
                ('Products', models.CharField(max_length=250)),
                ('Product_Count', models.IntegerField()),
                ('Amount', models.FloatField()),
                ('Billing_Employee', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Employee_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=15)),
                ('Mail_Id', models.EmailField(max_length=254)),
                ('Date_Of_Birth', models.CharField(max_length=10)),
                ('Mobile_Number', models.IntegerField(max_length=15)),
                ('Address', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=10)),
                ('Status', models.BooleanField(default=True)),
                ('Date_Of_Joining', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=10)),
                ('Sales', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('Product_Name', models.CharField(max_length=20)),
                ('Product_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Dealer_Mail_Id', models.EmailField(max_length=254)),
                ('Order_quantity', models.IntegerField()),
            ],
        ),
    ]
