# Generated by Django 3.1.2 on 2020-10-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20201030_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Date_Of_Birth',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='login',
            name='Date_Of_Joining',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='login',
            name='Mail_Id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='Mobile_Number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='login',
            name='Password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='login',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
