# Generated by Django 3.1.2 on 2020-10-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20201031_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Date_Of_Joining',
            field=models.CharField(max_length=25),
        ),
    ]
