# Generated by Django 3.1.2 on 2020-10-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20201031_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Mail_Id',
            field=models.CharField(max_length=35),
        ),
    ]
