# Generated by Django 3.1.2 on 2020-11-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_auto_20201106_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='Timestamp',
            field=models.CharField(max_length=30),
        ),
    ]
